version: '3'

services:
  build:
    build:
      context: ./web
      dockerfile: docker/build/Dockerfile
      args:
        - DEP_NOVA_XUI
    working_dir: /app
    container_name: "build"
    environment:
      - TEAMCITY_VERSION
    ports: 
      - "4200:4200"
      - "49153:49153"
    volumes:
      - "./web:/app"
      - /app/node_modules
  db:
    image: mongo:3
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
  api:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - MONGO_URL=db:27017/local
  web:
    build: 
      context: ./web
      dockerfile: docker/web/Dockerfile
    ports: 
      - "80:80"
    depends_on:
     - api
  selenium-chrome-standalone:
    image: "selenium/standalone-chrome-debug"
    ports:
      - "44444:4444"
      - "5900:5900"
    depends_on:
      - web
volumes:
  dbdata:
